/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiConnectorsRouteImport } from './routes/ai-connectors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedControlRouteImport } from './routes/_authenticated/control'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopHandleRouteImport } from './routes/shop.$handle'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedControlIndexRouteImport } from './routes/_authenticated/control.index'
import { Route as AuthenticatedControlAutomationsRouteImport } from './routes/_authenticated/control.automations'
import { Route as AuthenticatedControlCatalogueRouteImport } from './routes/_authenticated/control.catalogue'
import { Route as AuthenticatedControlChannelsRouteImport } from './routes/_authenticated/control.channels'
import { Route as AuthenticatedControlContactRouteImport } from './routes/_authenticated/control.contact'
import { Route as AuthenticatedControlIntakeRouteImport } from './routes/_authenticated/control.intake'
import { Route as AuthenticatedControlIntegrationsRouteImport } from './routes/_authenticated/control.integrations'
import { Route as AuthenticatedControlJournalRouteImport } from './routes/_authenticated/control.journal'
import { Route as AuthenticatedControlLegalRouteImport } from './routes/_authenticated/control.legal'
import { Route as AuthenticatedControlMcpRouteImport } from './routes/_authenticated/control.mcp'
import { Route as AuthenticatedControlOrdersRouteImport } from './routes/_authenticated/control.orders'
import { Route as AuthenticatedControlPreviewRouteImport } from './routes/_authenticated/control.preview'
import { Route as AuthenticatedControlPricingRouteImport } from './routes/_authenticated/control.pricing'
import { Route as AuthenticatedControlReviewsRouteImport } from './routes/_authenticated/control.reviews'
import { Route as AuthenticatedControlSeoRouteImport } from './routes/_authenticated/control.seo'
import { Route as AuthenticatedControlSourcingRouteImport } from './routes/_authenticated/control.sourcing'
import { Route as AuthenticatedControlJournalIndexRouteImport } from './routes/_authenticated/control.journal.index'
import { Route as AuthenticatedControlJournalArticleIdRouteImport } from './routes/_authenticated/control.journal.$articleId'
import { Route as AuthenticatedControlJournalNewRouteImport } from './routes/_authenticated/control.journal.new'
import { Route as AuthenticatedControlOrdersIndexRouteImport } from './routes/_authenticated/control.orders.index'
import { Route as AuthenticatedControlOrdersOrderIdRouteImport } from './routes/_authenticated/control.orders.$orderId'
import { Route as ApiPublicHooksAutomationRouteImport } from './routes/api/public/hooks/automation'
import { Route as ApiPublicHooksShopifyIntakeRouteImport } from './routes/api/public/hooks/shopify-intake'
import { Route as ApiPublicHooksShopifyOrdersRouteImport } from './routes/api/public/hooks/shopify-orders'
import { Route as ApiPublicJournalMediaSplatRouteImport } from './routes/api/public/journal-media.$'
import { Route as ApiPublicV1IndexRouteImport } from './routes/api/public/v1/index'
import { Route as ApiPublicV1AnswersRouteImport } from './routes/api/public/v1/answers'
import { Route as ApiPublicV1ArticlesRouteImport } from './routes/api/public/v1/articles'
import { Route as ApiPublicV1CollectionsRouteImport } from './routes/api/public/v1/collections'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1/products'
import { Route as ApiPublicV1StoreRouteImport } from './routes/api/public/v1/store'
import { Route as ApiPublicV1ArticlesSlugRouteImport } from './routes/api/public/v1/articles.$slug'
import { Route as ApiPublicV1PoliciesSlugRouteImport } from './routes/api/public/v1/policies.$slug'
import { Route as ApiPublicV1ProductsHandleRouteImport } from './routes/api/public/v1/products.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConnectorsRoute = AiConnectorsRouteImport.update({
  id: '/ai-connectors',
  path: '/ai-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedControlRoute = AuthenticatedControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopHandleRoute = ShopHandleRouteImport.update({
  id: '/shop/$handle',
  path: '/shop/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedControlIndexRoute =
  AuthenticatedControlIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlAutomationsRoute =
  AuthenticatedControlAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlCatalogueRoute =
  AuthenticatedControlCatalogueRouteImport.update({
    id: '/catalogue',
    path: '/catalogue',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlChannelsRoute =
  AuthenticatedControlChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlContactRoute =
  AuthenticatedControlContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlIntakeRoute =
  AuthenticatedControlIntakeRouteImport.update({
    id: '/intake',
    path: '/intake',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlIntegrationsRoute =
  AuthenticatedControlIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlJournalRoute =
  AuthenticatedControlJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlLegalRoute =
  AuthenticatedControlLegalRouteImport.update({
    id: '/legal',
    path: '/legal',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlMcpRoute = AuthenticatedControlMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedControlRoute,
} as any)
const AuthenticatedControlOrdersRoute =
  AuthenticatedControlOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlPreviewRoute =
  AuthenticatedControlPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlPricingRoute =
  AuthenticatedControlPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlReviewsRoute =
  AuthenticatedControlReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlSeoRoute = AuthenticatedControlSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedControlRoute,
} as any)
const AuthenticatedControlSourcingRoute =
  AuthenticatedControlSourcingRouteImport.update({
    id: '/sourcing',
    path: '/sourcing',
    getParentRoute: () => AuthenticatedControlRoute,
  } as any)
const AuthenticatedControlJournalIndexRoute =
  AuthenticatedControlJournalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedControlJournalRoute,
  } as any)
const AuthenticatedControlJournalArticleIdRoute =
  AuthenticatedControlJournalArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AuthenticatedControlJournalRoute,
  } as any)
const AuthenticatedControlJournalNewRoute =
  AuthenticatedControlJournalNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedControlJournalRoute,
  } as any)
const AuthenticatedControlOrdersIndexRoute =
  AuthenticatedControlOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedControlOrdersRoute,
  } as any)
const AuthenticatedControlOrdersOrderIdRoute =
  AuthenticatedControlOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedControlOrdersRoute,
  } as any)
const ApiPublicHooksAutomationRoute =
  ApiPublicHooksAutomationRouteImport.update({
    id: '/api/public/hooks/automation',
    path: '/api/public/hooks/automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShopifyIntakeRoute =
  ApiPublicHooksShopifyIntakeRouteImport.update({
    id: '/api/public/hooks/shopify-intake',
    path: '/api/public/hooks/shopify-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShopifyOrdersRoute =
  ApiPublicHooksShopifyOrdersRouteImport.update({
    id: '/api/public/hooks/shopify-orders',
    path: '/api/public/hooks/shopify-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJournalMediaSplatRoute =
  ApiPublicJournalMediaSplatRouteImport.update({
    id: '/api/public/journal-media/$',
    path: '/api/public/journal-media/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1IndexRoute = ApiPublicV1IndexRouteImport.update({
  id: '/api/public/v1/',
  path: '/api/public/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AnswersRoute = ApiPublicV1AnswersRouteImport.update({
  id: '/api/public/v1/answers',
  path: '/api/public/v1/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ArticlesRoute = ApiPublicV1ArticlesRouteImport.update({
  id: '/api/public/v1/articles',
  path: '/api/public/v1/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CollectionsRoute = ApiPublicV1CollectionsRouteImport.update({
  id: '/api/public/v1/collections',
  path: '/api/public/v1/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StoreRoute = ApiPublicV1StoreRouteImport.update({
  id: '/api/public/v1/store',
  path: '/api/public/v1/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ArticlesSlugRoute = ApiPublicV1ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicV1ArticlesRoute,
} as any)
const ApiPublicV1PoliciesSlugRoute = ApiPublicV1PoliciesSlugRouteImport.update({
  id: '/api/public/v1/policies/$slug',
  path: '/api/public/v1/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsHandleRoute =
  ApiPublicV1ProductsHandleRouteImport.update({
    id: '/$handle',
    path: '/$handle',
    getParentRoute: () => ApiPublicV1ProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-connectors': typeof AiConnectorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/control': typeof AuthenticatedControlRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/store/': typeof StoreIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/control/automations': typeof AuthenticatedControlAutomationsRoute
  '/control/catalogue': typeof AuthenticatedControlCatalogueRoute
  '/control/channels': typeof AuthenticatedControlChannelsRoute
  '/control/contact': typeof AuthenticatedControlContactRoute
  '/control/intake': typeof AuthenticatedControlIntakeRoute
  '/control/integrations': typeof AuthenticatedControlIntegrationsRoute
  '/control/journal': typeof AuthenticatedControlJournalRouteWithChildren
  '/control/legal': typeof AuthenticatedControlLegalRoute
  '/control/mcp': typeof AuthenticatedControlMcpRoute
  '/control/orders': typeof AuthenticatedControlOrdersRouteWithChildren
  '/control/preview': typeof AuthenticatedControlPreviewRoute
  '/control/pricing': typeof AuthenticatedControlPricingRoute
  '/control/reviews': typeof AuthenticatedControlReviewsRoute
  '/control/seo': typeof AuthenticatedControlSeoRoute
  '/control/sourcing': typeof AuthenticatedControlSourcingRoute
  '/control/': typeof AuthenticatedControlIndexRoute
  '/control/journal/$articleId': typeof AuthenticatedControlJournalArticleIdRoute
  '/control/journal/new': typeof AuthenticatedControlJournalNewRoute
  '/control/orders/$orderId': typeof AuthenticatedControlOrdersOrderIdRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/shopify-intake': typeof ApiPublicHooksShopifyIntakeRoute
  '/api/public/hooks/shopify-orders': typeof ApiPublicHooksShopifyOrdersRoute
  '/api/public/journal-media/$': typeof ApiPublicJournalMediaSplatRoute
  '/api/public/v1/answers': typeof ApiPublicV1AnswersRoute
  '/api/public/v1/articles': typeof ApiPublicV1ArticlesRouteWithChildren
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/store': typeof ApiPublicV1StoreRoute
  '/control/journal/': typeof AuthenticatedControlJournalIndexRoute
  '/control/orders/': typeof AuthenticatedControlOrdersIndexRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/v1/articles/$slug': typeof ApiPublicV1ArticlesSlugRoute
  '/api/public/v1/policies/$slug': typeof ApiPublicV1PoliciesSlugRoute
  '/api/public/v1/products/$handle': typeof ApiPublicV1ProductsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-connectors': typeof AiConnectorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/$': typeof AdminSplatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/collections': typeof CollectionsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/legal': typeof LegalIndexRoute
  '/shop': typeof ShopIndexRoute
  '/store': typeof StoreIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/control/automations': typeof AuthenticatedControlAutomationsRoute
  '/control/catalogue': typeof AuthenticatedControlCatalogueRoute
  '/control/channels': typeof AuthenticatedControlChannelsRoute
  '/control/contact': typeof AuthenticatedControlContactRoute
  '/control/intake': typeof AuthenticatedControlIntakeRoute
  '/control/integrations': typeof AuthenticatedControlIntegrationsRoute
  '/control/legal': typeof AuthenticatedControlLegalRoute
  '/control/mcp': typeof AuthenticatedControlMcpRoute
  '/control/preview': typeof AuthenticatedControlPreviewRoute
  '/control/pricing': typeof AuthenticatedControlPricingRoute
  '/control/reviews': typeof AuthenticatedControlReviewsRoute
  '/control/seo': typeof AuthenticatedControlSeoRoute
  '/control/sourcing': typeof AuthenticatedControlSourcingRoute
  '/control': typeof AuthenticatedControlIndexRoute
  '/control/journal/$articleId': typeof AuthenticatedControlJournalArticleIdRoute
  '/control/journal/new': typeof AuthenticatedControlJournalNewRoute
  '/control/orders/$orderId': typeof AuthenticatedControlOrdersOrderIdRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/shopify-intake': typeof ApiPublicHooksShopifyIntakeRoute
  '/api/public/hooks/shopify-orders': typeof ApiPublicHooksShopifyOrdersRoute
  '/api/public/journal-media/$': typeof ApiPublicJournalMediaSplatRoute
  '/api/public/v1/answers': typeof ApiPublicV1AnswersRoute
  '/api/public/v1/articles': typeof ApiPublicV1ArticlesRouteWithChildren
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/store': typeof ApiPublicV1StoreRoute
  '/control/journal': typeof AuthenticatedControlJournalIndexRoute
  '/control/orders': typeof AuthenticatedControlOrdersIndexRoute
  '/api/public/v1': typeof ApiPublicV1IndexRoute
  '/api/public/v1/articles/$slug': typeof ApiPublicV1ArticlesSlugRoute
  '/api/public/v1/policies/$slug': typeof ApiPublicV1PoliciesSlugRoute
  '/api/public/v1/products/$handle': typeof ApiPublicV1ProductsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-connectors': typeof AiConnectorsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/control': typeof AuthenticatedControlRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/store/': typeof StoreIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/control/automations': typeof AuthenticatedControlAutomationsRoute
  '/_authenticated/control/catalogue': typeof AuthenticatedControlCatalogueRoute
  '/_authenticated/control/channels': typeof AuthenticatedControlChannelsRoute
  '/_authenticated/control/contact': typeof AuthenticatedControlContactRoute
  '/_authenticated/control/intake': typeof AuthenticatedControlIntakeRoute
  '/_authenticated/control/integrations': typeof AuthenticatedControlIntegrationsRoute
  '/_authenticated/control/journal': typeof AuthenticatedControlJournalRouteWithChildren
  '/_authenticated/control/legal': typeof AuthenticatedControlLegalRoute
  '/_authenticated/control/mcp': typeof AuthenticatedControlMcpRoute
  '/_authenticated/control/orders': typeof AuthenticatedControlOrdersRouteWithChildren
  '/_authenticated/control/preview': typeof AuthenticatedControlPreviewRoute
  '/_authenticated/control/pricing': typeof AuthenticatedControlPricingRoute
  '/_authenticated/control/reviews': typeof AuthenticatedControlReviewsRoute
  '/_authenticated/control/seo': typeof AuthenticatedControlSeoRoute
  '/_authenticated/control/sourcing': typeof AuthenticatedControlSourcingRoute
  '/_authenticated/control/': typeof AuthenticatedControlIndexRoute
  '/_authenticated/control/journal/$articleId': typeof AuthenticatedControlJournalArticleIdRoute
  '/_authenticated/control/journal/new': typeof AuthenticatedControlJournalNewRoute
  '/_authenticated/control/orders/$orderId': typeof AuthenticatedControlOrdersOrderIdRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/shopify-intake': typeof ApiPublicHooksShopifyIntakeRoute
  '/api/public/hooks/shopify-orders': typeof ApiPublicHooksShopifyOrdersRoute
  '/api/public/journal-media/$': typeof ApiPublicJournalMediaSplatRoute
  '/api/public/v1/answers': typeof ApiPublicV1AnswersRoute
  '/api/public/v1/articles': typeof ApiPublicV1ArticlesRouteWithChildren
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/store': typeof ApiPublicV1StoreRoute
  '/_authenticated/control/journal/': typeof AuthenticatedControlJournalIndexRoute
  '/_authenticated/control/orders/': typeof AuthenticatedControlOrdersIndexRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/v1/articles/$slug': typeof ApiPublicV1ArticlesSlugRoute
  '/api/public/v1/policies/$slug': typeof ApiPublicV1PoliciesSlugRoute
  '/api/public/v1/products/$handle': typeof ApiPublicV1ProductsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-connectors'
    | '/auth'
    | '/contact'
    | '/llms.txt'
    | '/mcp'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/control'
    | '/admin/$'
    | '/category/$slug'
    | '/collections/$handle'
    | '/journal/$slug'
    | '/legal/$slug'
    | '/shop/$handle'
    | '/collections/'
    | '/journal/'
    | '/legal/'
    | '/shop/'
    | '/store/'
    | '/.mcp/invoke-tool/$tool'
    | '/control/automations'
    | '/control/catalogue'
    | '/control/channels'
    | '/control/contact'
    | '/control/intake'
    | '/control/integrations'
    | '/control/journal'
    | '/control/legal'
    | '/control/mcp'
    | '/control/orders'
    | '/control/preview'
    | '/control/pricing'
    | '/control/reviews'
    | '/control/seo'
    | '/control/sourcing'
    | '/control/'
    | '/control/journal/$articleId'
    | '/control/journal/new'
    | '/control/orders/$orderId'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/shopify-intake'
    | '/api/public/hooks/shopify-orders'
    | '/api/public/journal-media/$'
    | '/api/public/v1/answers'
    | '/api/public/v1/articles'
    | '/api/public/v1/collections'
    | '/api/public/v1/products'
    | '/api/public/v1/store'
    | '/control/journal/'
    | '/control/orders/'
    | '/api/public/v1/'
    | '/api/public/v1/articles/$slug'
    | '/api/public/v1/policies/$slug'
    | '/api/public/v1/products/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-connectors'
    | '/auth'
    | '/contact'
    | '/llms.txt'
    | '/mcp'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/$'
    | '/category/$slug'
    | '/collections/$handle'
    | '/journal/$slug'
    | '/legal/$slug'
    | '/shop/$handle'
    | '/collections'
    | '/journal'
    | '/legal'
    | '/shop'
    | '/store'
    | '/.mcp/invoke-tool/$tool'
    | '/control/automations'
    | '/control/catalogue'
    | '/control/channels'
    | '/control/contact'
    | '/control/intake'
    | '/control/integrations'
    | '/control/legal'
    | '/control/mcp'
    | '/control/preview'
    | '/control/pricing'
    | '/control/reviews'
    | '/control/seo'
    | '/control/sourcing'
    | '/control'
    | '/control/journal/$articleId'
    | '/control/journal/new'
    | '/control/orders/$orderId'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/shopify-intake'
    | '/api/public/hooks/shopify-orders'
    | '/api/public/journal-media/$'
    | '/api/public/v1/answers'
    | '/api/public/v1/articles'
    | '/api/public/v1/collections'
    | '/api/public/v1/products'
    | '/api/public/v1/store'
    | '/control/journal'
    | '/control/orders'
    | '/api/public/v1'
    | '/api/public/v1/articles/$slug'
    | '/api/public/v1/policies/$slug'
    | '/api/public/v1/products/$handle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/ai-connectors'
    | '/auth'
    | '/contact'
    | '/llms.txt'
    | '/mcp'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/control'
    | '/admin/$'
    | '/category/$slug'
    | '/collections/$handle'
    | '/journal/$slug'
    | '/legal/$slug'
    | '/shop/$handle'
    | '/collections/'
    | '/journal/'
    | '/legal/'
    | '/shop/'
    | '/store/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/control/automations'
    | '/_authenticated/control/catalogue'
    | '/_authenticated/control/channels'
    | '/_authenticated/control/contact'
    | '/_authenticated/control/intake'
    | '/_authenticated/control/integrations'
    | '/_authenticated/control/journal'
    | '/_authenticated/control/legal'
    | '/_authenticated/control/mcp'
    | '/_authenticated/control/orders'
    | '/_authenticated/control/preview'
    | '/_authenticated/control/pricing'
    | '/_authenticated/control/reviews'
    | '/_authenticated/control/seo'
    | '/_authenticated/control/sourcing'
    | '/_authenticated/control/'
    | '/_authenticated/control/journal/$articleId'
    | '/_authenticated/control/journal/new'
    | '/_authenticated/control/orders/$orderId'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/shopify-intake'
    | '/api/public/hooks/shopify-orders'
    | '/api/public/journal-media/$'
    | '/api/public/v1/answers'
    | '/api/public/v1/articles'
    | '/api/public/v1/collections'
    | '/api/public/v1/products'
    | '/api/public/v1/store'
    | '/_authenticated/control/journal/'
    | '/_authenticated/control/orders/'
    | '/api/public/v1/'
    | '/api/public/v1/articles/$slug'
    | '/api/public/v1/policies/$slug'
    | '/api/public/v1/products/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiConnectorsRoute: typeof AiConnectorsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  JournalSlugRoute: typeof JournalSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ShopHandleRoute: typeof ShopHandleRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksAutomationRoute: typeof ApiPublicHooksAutomationRoute
  ApiPublicHooksShopifyIntakeRoute: typeof ApiPublicHooksShopifyIntakeRoute
  ApiPublicHooksShopifyOrdersRoute: typeof ApiPublicHooksShopifyOrdersRoute
  ApiPublicJournalMediaSplatRoute: typeof ApiPublicJournalMediaSplatRoute
  ApiPublicV1AnswersRoute: typeof ApiPublicV1AnswersRoute
  ApiPublicV1ArticlesRoute: typeof ApiPublicV1ArticlesRouteWithChildren
  ApiPublicV1CollectionsRoute: typeof ApiPublicV1CollectionsRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRouteWithChildren
  ApiPublicV1StoreRoute: typeof ApiPublicV1StoreRoute
  ApiPublicV1IndexRoute: typeof ApiPublicV1IndexRoute
  ApiPublicV1PoliciesSlugRoute: typeof ApiPublicV1PoliciesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-connectors': {
      id: '/ai-connectors'
      path: '/ai-connectors'
      fullPath: '/ai-connectors'
      preLoaderRoute: typeof AiConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/control': {
      id: '/_authenticated/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof AuthenticatedControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$handle': {
      id: '/shop/$handle'
      path: '/shop/$handle'
      fullPath: '/shop/$handle'
      preLoaderRoute: typeof ShopHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/control/': {
      id: '/_authenticated/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof AuthenticatedControlIndexRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/automations': {
      id: '/_authenticated/control/automations'
      path: '/automations'
      fullPath: '/control/automations'
      preLoaderRoute: typeof AuthenticatedControlAutomationsRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/catalogue': {
      id: '/_authenticated/control/catalogue'
      path: '/catalogue'
      fullPath: '/control/catalogue'
      preLoaderRoute: typeof AuthenticatedControlCatalogueRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/channels': {
      id: '/_authenticated/control/channels'
      path: '/channels'
      fullPath: '/control/channels'
      preLoaderRoute: typeof AuthenticatedControlChannelsRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/contact': {
      id: '/_authenticated/control/contact'
      path: '/contact'
      fullPath: '/control/contact'
      preLoaderRoute: typeof AuthenticatedControlContactRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/intake': {
      id: '/_authenticated/control/intake'
      path: '/intake'
      fullPath: '/control/intake'
      preLoaderRoute: typeof AuthenticatedControlIntakeRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/integrations': {
      id: '/_authenticated/control/integrations'
      path: '/integrations'
      fullPath: '/control/integrations'
      preLoaderRoute: typeof AuthenticatedControlIntegrationsRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/journal': {
      id: '/_authenticated/control/journal'
      path: '/journal'
      fullPath: '/control/journal'
      preLoaderRoute: typeof AuthenticatedControlJournalRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/legal': {
      id: '/_authenticated/control/legal'
      path: '/legal'
      fullPath: '/control/legal'
      preLoaderRoute: typeof AuthenticatedControlLegalRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/mcp': {
      id: '/_authenticated/control/mcp'
      path: '/mcp'
      fullPath: '/control/mcp'
      preLoaderRoute: typeof AuthenticatedControlMcpRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/orders': {
      id: '/_authenticated/control/orders'
      path: '/orders'
      fullPath: '/control/orders'
      preLoaderRoute: typeof AuthenticatedControlOrdersRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/preview': {
      id: '/_authenticated/control/preview'
      path: '/preview'
      fullPath: '/control/preview'
      preLoaderRoute: typeof AuthenticatedControlPreviewRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/pricing': {
      id: '/_authenticated/control/pricing'
      path: '/pricing'
      fullPath: '/control/pricing'
      preLoaderRoute: typeof AuthenticatedControlPricingRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/reviews': {
      id: '/_authenticated/control/reviews'
      path: '/reviews'
      fullPath: '/control/reviews'
      preLoaderRoute: typeof AuthenticatedControlReviewsRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/seo': {
      id: '/_authenticated/control/seo'
      path: '/seo'
      fullPath: '/control/seo'
      preLoaderRoute: typeof AuthenticatedControlSeoRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/sourcing': {
      id: '/_authenticated/control/sourcing'
      path: '/sourcing'
      fullPath: '/control/sourcing'
      preLoaderRoute: typeof AuthenticatedControlSourcingRouteImport
      parentRoute: typeof AuthenticatedControlRoute
    }
    '/_authenticated/control/journal/': {
      id: '/_authenticated/control/journal/'
      path: '/'
      fullPath: '/control/journal/'
      preLoaderRoute: typeof AuthenticatedControlJournalIndexRouteImport
      parentRoute: typeof AuthenticatedControlJournalRoute
    }
    '/_authenticated/control/journal/$articleId': {
      id: '/_authenticated/control/journal/$articleId'
      path: '/$articleId'
      fullPath: '/control/journal/$articleId'
      preLoaderRoute: typeof AuthenticatedControlJournalArticleIdRouteImport
      parentRoute: typeof AuthenticatedControlJournalRoute
    }
    '/_authenticated/control/journal/new': {
      id: '/_authenticated/control/journal/new'
      path: '/new'
      fullPath: '/control/journal/new'
      preLoaderRoute: typeof AuthenticatedControlJournalNewRouteImport
      parentRoute: typeof AuthenticatedControlJournalRoute
    }
    '/_authenticated/control/orders/': {
      id: '/_authenticated/control/orders/'
      path: '/'
      fullPath: '/control/orders/'
      preLoaderRoute: typeof AuthenticatedControlOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedControlOrdersRoute
    }
    '/_authenticated/control/orders/$orderId': {
      id: '/_authenticated/control/orders/$orderId'
      path: '/$orderId'
      fullPath: '/control/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedControlOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedControlOrdersRoute
    }
    '/api/public/hooks/automation': {
      id: '/api/public/hooks/automation'
      path: '/api/public/hooks/automation'
      fullPath: '/api/public/hooks/automation'
      preLoaderRoute: typeof ApiPublicHooksAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shopify-intake': {
      id: '/api/public/hooks/shopify-intake'
      path: '/api/public/hooks/shopify-intake'
      fullPath: '/api/public/hooks/shopify-intake'
      preLoaderRoute: typeof ApiPublicHooksShopifyIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shopify-orders': {
      id: '/api/public/hooks/shopify-orders'
      path: '/api/public/hooks/shopify-orders'
      fullPath: '/api/public/hooks/shopify-orders'
      preLoaderRoute: typeof ApiPublicHooksShopifyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/journal-media/$': {
      id: '/api/public/journal-media/$'
      path: '/api/public/journal-media/$'
      fullPath: '/api/public/journal-media/$'
      preLoaderRoute: typeof ApiPublicJournalMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/': {
      id: '/api/public/v1/'
      path: '/api/public/v1'
      fullPath: '/api/public/v1/'
      preLoaderRoute: typeof ApiPublicV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/answers': {
      id: '/api/public/v1/answers'
      path: '/api/public/v1/answers'
      fullPath: '/api/public/v1/answers'
      preLoaderRoute: typeof ApiPublicV1AnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/articles': {
      id: '/api/public/v1/articles'
      path: '/api/public/v1/articles'
      fullPath: '/api/public/v1/articles'
      preLoaderRoute: typeof ApiPublicV1ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/collections': {
      id: '/api/public/v1/collections'
      path: '/api/public/v1/collections'
      fullPath: '/api/public/v1/collections'
      preLoaderRoute: typeof ApiPublicV1CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/store': {
      id: '/api/public/v1/store'
      path: '/api/public/v1/store'
      fullPath: '/api/public/v1/store'
      preLoaderRoute: typeof ApiPublicV1StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/articles/$slug': {
      id: '/api/public/v1/articles/$slug'
      path: '/$slug'
      fullPath: '/api/public/v1/articles/$slug'
      preLoaderRoute: typeof ApiPublicV1ArticlesSlugRouteImport
      parentRoute: typeof ApiPublicV1ArticlesRoute
    }
    '/api/public/v1/policies/$slug': {
      id: '/api/public/v1/policies/$slug'
      path: '/api/public/v1/policies/$slug'
      fullPath: '/api/public/v1/policies/$slug'
      preLoaderRoute: typeof ApiPublicV1PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/$handle': {
      id: '/api/public/v1/products/$handle'
      path: '/$handle'
      fullPath: '/api/public/v1/products/$handle'
      preLoaderRoute: typeof ApiPublicV1ProductsHandleRouteImport
      parentRoute: typeof ApiPublicV1ProductsRoute
    }
  }
}

interface AuthenticatedControlJournalRouteChildren {
  AuthenticatedControlJournalArticleIdRoute: typeof AuthenticatedControlJournalArticleIdRoute
  AuthenticatedControlJournalNewRoute: typeof AuthenticatedControlJournalNewRoute
  AuthenticatedControlJournalIndexRoute: typeof AuthenticatedControlJournalIndexRoute
}

const AuthenticatedControlJournalRouteChildren: AuthenticatedControlJournalRouteChildren =
  {
    AuthenticatedControlJournalArticleIdRoute:
      AuthenticatedControlJournalArticleIdRoute,
    AuthenticatedControlJournalNewRoute: AuthenticatedControlJournalNewRoute,
    AuthenticatedControlJournalIndexRoute:
      AuthenticatedControlJournalIndexRoute,
  }

const AuthenticatedControlJournalRouteWithChildren =
  AuthenticatedControlJournalRoute._addFileChildren(
    AuthenticatedControlJournalRouteChildren,
  )

interface AuthenticatedControlOrdersRouteChildren {
  AuthenticatedControlOrdersOrderIdRoute: typeof AuthenticatedControlOrdersOrderIdRoute
  AuthenticatedControlOrdersIndexRoute: typeof AuthenticatedControlOrdersIndexRoute
}

const AuthenticatedControlOrdersRouteChildren: AuthenticatedControlOrdersRouteChildren =
  {
    AuthenticatedControlOrdersOrderIdRoute:
      AuthenticatedControlOrdersOrderIdRoute,
    AuthenticatedControlOrdersIndexRoute: AuthenticatedControlOrdersIndexRoute,
  }

const AuthenticatedControlOrdersRouteWithChildren =
  AuthenticatedControlOrdersRoute._addFileChildren(
    AuthenticatedControlOrdersRouteChildren,
  )

interface AuthenticatedControlRouteChildren {
  AuthenticatedControlAutomationsRoute: typeof AuthenticatedControlAutomationsRoute
  AuthenticatedControlCatalogueRoute: typeof AuthenticatedControlCatalogueRoute
  AuthenticatedControlChannelsRoute: typeof AuthenticatedControlChannelsRoute
  AuthenticatedControlContactRoute: typeof AuthenticatedControlContactRoute
  AuthenticatedControlIntakeRoute: typeof AuthenticatedControlIntakeRoute
  AuthenticatedControlIntegrationsRoute: typeof AuthenticatedControlIntegrationsRoute
  AuthenticatedControlJournalRoute: typeof AuthenticatedControlJournalRouteWithChildren
  AuthenticatedControlLegalRoute: typeof AuthenticatedControlLegalRoute
  AuthenticatedControlMcpRoute: typeof AuthenticatedControlMcpRoute
  AuthenticatedControlOrdersRoute: typeof AuthenticatedControlOrdersRouteWithChildren
  AuthenticatedControlPreviewRoute: typeof AuthenticatedControlPreviewRoute
  AuthenticatedControlPricingRoute: typeof AuthenticatedControlPricingRoute
  AuthenticatedControlReviewsRoute: typeof AuthenticatedControlReviewsRoute
  AuthenticatedControlSeoRoute: typeof AuthenticatedControlSeoRoute
  AuthenticatedControlSourcingRoute: typeof AuthenticatedControlSourcingRoute
  AuthenticatedControlIndexRoute: typeof AuthenticatedControlIndexRoute
}

const AuthenticatedControlRouteChildren: AuthenticatedControlRouteChildren = {
  AuthenticatedControlAutomationsRoute: AuthenticatedControlAutomationsRoute,
  AuthenticatedControlCatalogueRoute: AuthenticatedControlCatalogueRoute,
  AuthenticatedControlChannelsRoute: AuthenticatedControlChannelsRoute,
  AuthenticatedControlContactRoute: AuthenticatedControlContactRoute,
  AuthenticatedControlIntakeRoute: AuthenticatedControlIntakeRoute,
  AuthenticatedControlIntegrationsRoute: AuthenticatedControlIntegrationsRoute,
  AuthenticatedControlJournalRoute:
    AuthenticatedControlJournalRouteWithChildren,
  AuthenticatedControlLegalRoute: AuthenticatedControlLegalRoute,
  AuthenticatedControlMcpRoute: AuthenticatedControlMcpRoute,
  AuthenticatedControlOrdersRoute: AuthenticatedControlOrdersRouteWithChildren,
  AuthenticatedControlPreviewRoute: AuthenticatedControlPreviewRoute,
  AuthenticatedControlPricingRoute: AuthenticatedControlPricingRoute,
  AuthenticatedControlReviewsRoute: AuthenticatedControlReviewsRoute,
  AuthenticatedControlSeoRoute: AuthenticatedControlSeoRoute,
  AuthenticatedControlSourcingRoute: AuthenticatedControlSourcingRoute,
  AuthenticatedControlIndexRoute: AuthenticatedControlIndexRoute,
}

const AuthenticatedControlRouteWithChildren =
  AuthenticatedControlRoute._addFileChildren(AuthenticatedControlRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedControlRoute: typeof AuthenticatedControlRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedControlRoute: AuthenticatedControlRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPublicV1ArticlesRouteChildren {
  ApiPublicV1ArticlesSlugRoute: typeof ApiPublicV1ArticlesSlugRoute
}

const ApiPublicV1ArticlesRouteChildren: ApiPublicV1ArticlesRouteChildren = {
  ApiPublicV1ArticlesSlugRoute: ApiPublicV1ArticlesSlugRoute,
}

const ApiPublicV1ArticlesRouteWithChildren =
  ApiPublicV1ArticlesRoute._addFileChildren(ApiPublicV1ArticlesRouteChildren)

interface ApiPublicV1ProductsRouteChildren {
  ApiPublicV1ProductsHandleRoute: typeof ApiPublicV1ProductsHandleRoute
}

const ApiPublicV1ProductsRouteChildren: ApiPublicV1ProductsRouteChildren = {
  ApiPublicV1ProductsHandleRoute: ApiPublicV1ProductsHandleRoute,
}

const ApiPublicV1ProductsRouteWithChildren =
  ApiPublicV1ProductsRoute._addFileChildren(ApiPublicV1ProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiConnectorsRoute: AiConnectorsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CategorySlugRoute: CategorySlugRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  JournalSlugRoute: JournalSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ShopHandleRoute: ShopHandleRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksAutomationRoute: ApiPublicHooksAutomationRoute,
  ApiPublicHooksShopifyIntakeRoute: ApiPublicHooksShopifyIntakeRoute,
  ApiPublicHooksShopifyOrdersRoute: ApiPublicHooksShopifyOrdersRoute,
  ApiPublicJournalMediaSplatRoute: ApiPublicJournalMediaSplatRoute,
  ApiPublicV1AnswersRoute: ApiPublicV1AnswersRoute,
  ApiPublicV1ArticlesRoute: ApiPublicV1ArticlesRouteWithChildren,
  ApiPublicV1CollectionsRoute: ApiPublicV1CollectionsRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRouteWithChildren,
  ApiPublicV1StoreRoute: ApiPublicV1StoreRoute,
  ApiPublicV1IndexRoute: ApiPublicV1IndexRoute,
  ApiPublicV1PoliciesSlugRoute: ApiPublicV1PoliciesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
