/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin.automations'
import { Route as AuthenticatedAdminCatalogueRouteImport } from './routes/_authenticated/admin.catalogue'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin.journal'
import { Route as AuthenticatedAdminLegalRouteImport } from './routes/_authenticated/admin.legal'
import { Route as AuthenticatedAdminMcpRouteImport } from './routes/_authenticated/admin.mcp'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin.reviews'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminJournalIndexRouteImport } from './routes/_authenticated/admin.journal.index'
import { Route as AuthenticatedAdminJournalArticleIdRouteImport } from './routes/_authenticated/admin.journal.$articleId'
import { Route as AuthenticatedAdminJournalNewRouteImport } from './routes/_authenticated/admin.journal.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogueRoute =
  AuthenticatedAdminCatalogueRouteImport.update({
    id: '/catalogue',
    path: '/catalogue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLegalRoute = AuthenticatedAdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMcpRoute = AuthenticatedAdminMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminJournalIndexRoute =
  AuthenticatedAdminJournalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminJournalRoute,
  } as any)
const AuthenticatedAdminJournalArticleIdRoute =
  AuthenticatedAdminJournalArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AuthenticatedAdminJournalRoute,
  } as any)
const AuthenticatedAdminJournalNewRoute =
  AuthenticatedAdminJournalNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminJournalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRouteWithChildren
  '/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/admin/mcp': typeof AuthenticatedAdminMcpRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/journal/$articleId': typeof AuthenticatedAdminJournalArticleIdRoute
  '/admin/journal/new': typeof AuthenticatedAdminJournalNewRoute
  '/admin/journal/': typeof AuthenticatedAdminJournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal': typeof JournalIndexRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/admin/mcp': typeof AuthenticatedAdminMcpRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/journal/$articleId': typeof AuthenticatedAdminJournalArticleIdRoute
  '/admin/journal/new': typeof AuthenticatedAdminJournalNewRoute
  '/admin/journal': typeof AuthenticatedAdminJournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRouteWithChildren
  '/_authenticated/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/_authenticated/admin/mcp': typeof AuthenticatedAdminMcpRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/journal/$articleId': typeof AuthenticatedAdminJournalArticleIdRoute
  '/_authenticated/admin/journal/new': typeof AuthenticatedAdminJournalNewRoute
  '/_authenticated/admin/journal/': typeof AuthenticatedAdminJournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/journal/$slug'
    | '/journal/'
    | '/admin/automations'
    | '/admin/catalogue'
    | '/admin/integrations'
    | '/admin/journal'
    | '/admin/legal'
    | '/admin/mcp'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/'
    | '/admin/journal/$articleId'
    | '/admin/journal/new'
    | '/admin/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/journal/$slug'
    | '/journal'
    | '/admin/automations'
    | '/admin/catalogue'
    | '/admin/integrations'
    | '/admin/legal'
    | '/admin/mcp'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin'
    | '/admin/journal/$articleId'
    | '/admin/journal/new'
    | '/admin/journal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/journal/$slug'
    | '/journal/'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/catalogue'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/legal'
    | '/_authenticated/admin/mcp'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/journal/$articleId'
    | '/_authenticated/admin/journal/new'
    | '/_authenticated/admin/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogue': {
      id: '/_authenticated/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/legal': {
      id: '/_authenticated/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AuthenticatedAdminLegalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mcp': {
      id: '/_authenticated/admin/mcp'
      path: '/mcp'
      fullPath: '/admin/mcp'
      preLoaderRoute: typeof AuthenticatedAdminMcpRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal/': {
      id: '/_authenticated/admin/journal/'
      path: '/'
      fullPath: '/admin/journal/'
      preLoaderRoute: typeof AuthenticatedAdminJournalIndexRouteImport
      parentRoute: typeof AuthenticatedAdminJournalRoute
    }
    '/_authenticated/admin/journal/$articleId': {
      id: '/_authenticated/admin/journal/$articleId'
      path: '/$articleId'
      fullPath: '/admin/journal/$articleId'
      preLoaderRoute: typeof AuthenticatedAdminJournalArticleIdRouteImport
      parentRoute: typeof AuthenticatedAdminJournalRoute
    }
    '/_authenticated/admin/journal/new': {
      id: '/_authenticated/admin/journal/new'
      path: '/new'
      fullPath: '/admin/journal/new'
      preLoaderRoute: typeof AuthenticatedAdminJournalNewRouteImport
      parentRoute: typeof AuthenticatedAdminJournalRoute
    }
  }
}

interface AuthenticatedAdminJournalRouteChildren {
  AuthenticatedAdminJournalArticleIdRoute: typeof AuthenticatedAdminJournalArticleIdRoute
  AuthenticatedAdminJournalNewRoute: typeof AuthenticatedAdminJournalNewRoute
  AuthenticatedAdminJournalIndexRoute: typeof AuthenticatedAdminJournalIndexRoute
}

const AuthenticatedAdminJournalRouteChildren: AuthenticatedAdminJournalRouteChildren =
  {
    AuthenticatedAdminJournalArticleIdRoute:
      AuthenticatedAdminJournalArticleIdRoute,
    AuthenticatedAdminJournalNewRoute: AuthenticatedAdminJournalNewRoute,
    AuthenticatedAdminJournalIndexRoute: AuthenticatedAdminJournalIndexRoute,
  }

const AuthenticatedAdminJournalRouteWithChildren =
  AuthenticatedAdminJournalRoute._addFileChildren(
    AuthenticatedAdminJournalRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminCatalogueRoute: typeof AuthenticatedAdminCatalogueRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRouteWithChildren
  AuthenticatedAdminLegalRoute: typeof AuthenticatedAdminLegalRoute
  AuthenticatedAdminMcpRoute: typeof AuthenticatedAdminMcpRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
  AuthenticatedAdminCatalogueRoute: AuthenticatedAdminCatalogueRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRouteWithChildren,
  AuthenticatedAdminLegalRoute: AuthenticatedAdminLegalRoute,
  AuthenticatedAdminMcpRoute: AuthenticatedAdminMcpRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
